# Generated by Django 2.2.12 on 2020-05-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='link_text',
            field=models.URLField(blank=True, default='shop now', null=True),
        ),
    ]
