# Generated by Django 2.2.12 on 2020-05-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_carousel_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='link_text',
            field=models.CharField(blank=True, default='shop now', max_length=50, null=True),
        ),
    ]
