# Generated by Django 2.2.12 on 2020-05-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200516_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='content',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='sub_content',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='sub_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
