# Generated by Django 2.2.12 on 2020-05-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200516_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='content',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='sub_content',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
