# Generated by Django 2.2.12 on 2020-05-12 13:33

from django.db import migrations, models
import django.db.models.deletion
import util.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('discount_type', models.CharField(choices=[('No Discount', 'No Discount'), ('Amount', 'Amount'), ('Percentage', 'Percentage')], default='No Discount', max_length=30)),
                ('expired_type', models.CharField(choices=[('On Date', 'On Date'), ('Date Range', 'Date Range'), ('No Expired', 'No Expired')], default='No Expired', max_length=30)),
                ('expired', models.DateField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=util.util.scramble_upload_filename)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('search_text', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('discount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Discount')),
            ],
        ),
    ]
