# Generated by Django 2.2.12 on 2020-05-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('Disable', 'Disable'), ('Amount', 'Amount'), ('Percentage', 'Percentage')], default='Percentage', max_length=30),
        ),
    ]
