# Generated by Django 2.2.12 on 2020-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200512_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('Amount', 'Amount'), ('Percentage', 'Percentage')], default='Percentage', max_length=30),
        ),
    ]
