# Generated by Django 2.2.12 on 2020-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200512_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='product.Product'),
        ),
    ]
