# Generated by Django 2.2.12 on 2020-05-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200512_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum',
            field=models.IntegerField(default=0.0),
        ),
    ]
